language: csharp
mono: none
dotnet: 2.0.0
script:
  - dotnet restore
  - npm --prefix ./GeekHunters/ run build
  - npm install
  - dotnet build ./GeekHunters/
  - dotnet test ./GeekHunters.UnitTests/
